### ISSUE TITLE
TODO: Implement createRequest() method.

### ISSUE THREAD

**Issue by sshilko** [maff/zf1-psr-7-bridge#1]
👍

**Comment by maff** [comment]
Hey,

this project is unmaintained - but feel free to fork or create a PR :)

Cheers,
Mathias

**Comment by sshilko** [comment]
ok, just fyi,
 i was able to convert Zend_Http_Adapter_Test write() method result into PSR-7 compatible str representation accepted by PSR-7 Guzzle unserializer
